### ISSUE TITLE
JSON Output format argument

### ISSUE THREAD

**Issue by srivasd** [alopezna5/mASAPP_CI#23]
Hi @alopezna5 ! We would find very useful a JSON output format option for every type of analysis. The request is detailed here:

**STEPS TO REPRODUCE**
1. Execute massapCI using standard, detailed standard, riskscoring or detailed riskscoring analysis.
2. See the results

**EXPECTED RESULT**
We would expect here to get some structured information in an output file.

**ACTUAL RESULT**
The detailed information is printed by console.

**PROPOSED SOLUTION**
The proposed improvement is to include an argument like **--output results.json** that can allow us to extract the information from scanResults/ in the corresponding JSON format.

Thanks,
Sergio.

**Comment by alopezna5** [comment]
Hi @srivasd !

I have one doubt: Do you only need yo store in a JSON the mASAPP output (vulnerabilities/behaviors/evidences...) or do you need too the mASAPP CI output (mASAPP output + number of expected vulnerabilities vs number of obtained vulnerabilities + number of expected behaviors vs number of obtained behaviors) ?

Thanks for your request 😄  I hope to solve it soon,
Álvaro

**Comment by srivasd** [comment]
> Hi @srivasd !
> 
> I have one doubt: Do you only need yo store in a JSON the mASAPP output (vulnerabilities/behaviors/evidences...) or do you need too the mASAPP CI output (mASAPP output + number of expected vulnerabilities vs number of obtained vulnerabilities + number of expected behaviors vs number of obtained behaviors) ?
> 
> Thanks for your request 😄 I hope to solve it soon,
> Álvaro

Hi @alopezna5 !

Thanks for the quick response. The idea is the first one. mASAPP API has the /scanresults call with the output results in a json format. We need that output but using directly mASAPP CI. 

Thanks again,

Sergio

**Comment by alopezna5** [comment]
@srivasd  mASAPP CI v1.3 has been released, your new feature should be available  :smile:

New usage:

```
$ masappcli --help
usage: masappcli [-h] [-a .ipa/.apk] [-key mASAPP_key] [-secret mASAPP_secret] [-p packageNameOrigin] [-r N] [-d] [-s .json] [-c] [-w workgroup name] [--export_summary *.json] [--export_result *.json]

                        _____           _____   _____      _____  __      _____   
                /\     / ____|   /\    |  __ \ |  __ \    / ____||  |    |_   _|  
  _ __ ___     /  \   | (___    /  \   | |__) || |__) |  | |     |  |      | |    
 | '_ ` _ \   / /\ \   \___ \  / /\ \  |  ___/ |  ___/   | |     |  |      | |    
 | | | | | | / ____ \  ____) |/ ____ \ | |     | |       | |____ |  |___  _| |_   
 |_| |_| |_|/_/    \_\|_____//_/    \_\|_|     |_|        \_____||______||_____|  

optional arguments:
  -h, --help            show this help message and exit
  -a .ipa/.apk, --app .ipa/.apk
                        path to the .apk or .ipa file
  -key mASAPP_key
  -secret mASAPP_secret
  -p packageNameOrigin, --packageNameOrigin packageNameOrigin
                        package name origin of the app
  -r N, --riskscore N   riskscoring execution
  -d, --detailed        add details to the execution
  -s .json, --standard .json
                        standard execution
  -c, --configure       add your mASAPP key and mASAPP secret as environment vars
  -w workgroup name, --workgroup workgroup name
                        the name of the workgroup you want to analyse in
  --export_summary *.json
                        export the scan summary from mASAPP in a json file
  --export_result *.json
``` 

export_summary and export_result are the params you are looking for

**Comment by alopezna5** [comment]
@srivasd 
Please, confirm if it is what you were looking for
